services:
  # web:
  #   build: ./web
  #   ports:
  #     - 3000:3000
  #   depends_on:
  #     - postgres
  #   environment:
  #     AUTH_SECRET: "TeeTuanmuan"
  #     DATABASE_URL: "postgresql://postgres:GaythaiPassmanStandardboy@postgres/schedule-api-v2"
  #   volumes:
  #     # for development
  #     - ./web/components:/usr/src/app/components
  #     - ./web/composables:/usr/src/app/composables
  #     - ./web/layouts:/usr/src/app/layouts
  #     - ./web/pages:/usr/src/app/pages
  #     - ./web/plugins:/usr/src/app/plugins
  #     - ./web/server:/usr/src/app/server
  #     - ./web/types:/usr/src/app/types
  #     - ./web/utils:/usr/src/app/utils
  #     - ./web/public:/usr/src/public
  #     # Fuck other file
  #   # command: "npx prisma db push & npm"
  rust-server:
    build:
      context: ./server/rust
      target: final
    ports:
      - "4574:4574"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: "postgresql://postgres:GaythaiPassmanStandardboy@postgres/schedule-api-v2"

  postgres:
    image: "postgres"
    restart: always
    environment:
      - POSTGRES_PASSWORD=GaythaiPassmanStandardboy
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

volumes:
  pgdata:
